version: '3.8'

services:

  db:
    image: postgres:17-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=silo
      - POSTGRES_PASSWORD=silo
      - POSTGRES_DB=silo-v2
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
